# Generated by Django 2.2 on 2021-04-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goals',
            field=models.TextField(null=True),
        ),
    ]
