# Generated by Django 2.2 on 2021-04-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges_app', '0003_auto_20210414_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='daily_increase',
            field=models.IntegerField(),
        ),
    ]
