# Generated by Django 2.2 on 2021-04-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges_app', '0004_auto_20210414_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='users_completed',
            field=models.ManyToManyField(related_name='challenges_completed', to='challenges_app.User'),
        ),
    ]
